### ISSUE TITLE
Vulnerable package detected

### ISSUE THREAD

**Issue by Daeer-Projects** [Daeer-Projects/DatabaseOperations#91]
**Describe the bug**
Vulnerabilities have been detected.

* Vulnerability in Microsoft.Identity.Client 4.60.3.
* Vulnerability in Azure.Identity 1.11.2.

**Comment by Daeer-Projects** [comment]
I'm not sure when I can do this. I hope to do it soon, but might not happen till later in June.

**Comment by aalgrou** [comment]
I fixed it for you, check

**Comment by Daeer-Projects** [comment]
Thank you.

I've only just got back home from NDC Oslo.

I'll get a release going soon.
😀
